import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="min-h-screen">
      <body className={clsx(inter.className, "min-h-screen w-full p-0 bg-[#fce1c7]", { 
        "debug-screens": process.env.NODE_ENV === "development"
      })}>
        {children}
      </body>
    </html>
  );
}
